version: '3.2'

services:
#########################################
# node core api instance
#########################################
  api:
    image: carbagar:${IMAGE_TAG}
    container_name: carbagar_api_${IMAGE_TAG}
    restart: always
    env_file:
      - .env
    ports:
      - 4001:4001
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "GET", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

#########################################
# networks
#########################################
networks:
  app-network:
    driver: bridge
